-- SELECT A.ANIMAL_ID,
--         A.NAME
-- FROM ANIMAL_INS A
-- RIGHT JOIN ANIMAL_OUTS B
-- ON A.NAME = B.NAME
-- WHERE 1=1
-- AND A.NAME IS NULL
-- AND B.NAME IS NOT NULL
-- ORDER BY B.animal_id, B.NAME

-- 입양보낸 동물 정보 ANIMAL_OUTS
-- 보호소에 들어온 동물 정보 ANIMAL_INS
-- 보호소 기록이 없는 동물 정보가 필요

SELECT A.ANIMAL_ID,
        A.NAME
FROM ANIMAL_OUTS A
LEFT JOIN ANIMAL_INS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE 1=1
AND B.animal_id IS NULL
ORDER BY A.ANIMAL_ID, NAME