-- # -- 코드를 입력하세요

-- # SELECT B.USER_ID AS USER_ID,
-- #     B.NICKNAME AS NICKNAME,
-- #     A.PRICE AS TOTAL_SALES
-- # FROM(
-- # SELECT *
-- # FROM USED_GOODS_BOARD
-- # WHERE 1=1
-- # AND PRICE >= 700000
-- # AND STATUS = 'DONE'
-- #     ) A
-- # LEFT JOIN  USED_GOODS_USER B
-- # ON A.WRITER_ID = B.USER_ID
-- # ORDER BY PRICE

SELECT B.USER_ID,
        B.NICKNAME,
        A.PRICE
FROM(
SELECT WRITER_ID,
    SUM(PRICE) AS PRICE
FROM USED_GOODS_BOARD
WHERE 1=1
AND STATUS = 'DONE'
GROUP BY WRITER_ID
    ) A
LEFT JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE 1=1
AND A.PRICE >= 700000
ORDER BY A.PRICE
