-- 코드를 입력하세요

SELECT *
FROM(
SELECT A.PRODUCT_CODE,
        A.PRICE * SUM(SALES_AMOUNT) AS SALES
FROM PRODUCT A
LEFT JOIN OFFLINE_SALE B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE, A.PRICE
)
ORDER BY SALES DESC, PRODUCT_CODE


-- SELECT *
-- FROM PRODUCT