-- 코드를 입력하세요
SELECT TO_NUMBER(DATETIME),
        COUNT(*) AS COUNT
FROM(
SELECT TO_CHAR(DATETIME, 'HH24') AS DATETIME
FROM ANIMAL_OUTS
)
WHERE DATETIME > 8 AND DATETIME<20
GROUP BY DATETIME
ORDER BY DATETIME
