-- 코드를 입력하세요
SELECT DISTINCT(CAR_ID)
FROM(
SELECT A.CAR_ID,
        A.CAR_TYPE,
        TO_CHAR(B.START_DATE,'YYYY-MM-DD') AS START_DATE
FROM CAR_RENTAL_COMPANY_CAR A
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY  B
ON A.CAR_ID = B.CAR_ID
)
WHERE 1=1
AND START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
AND CAR_TYPE = '세단'
ORDER BY CAR_ID DESC